# -*- coding: utf-8 -*-
"""detect_coutnours.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XKnD-i-StbKPvWfigjpuGdfBmqV3kGzg
"""

import cv2

import numpy as np

from google.colab.patches import cv2_imshow

image = cv2.imread('/content/streets.jpg')

cv2_imshow(image)

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
  
edged = cv2.Canny(gray, 20, 400)
contours, hierarchy = cv2.findContours(edged, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
  
cv2_imshow(edged)
  
print("Number of Contours found = " + str(len(contours)))
  
cv2.drawContours(image, contours, -1, (0, 255, 0), 3)
  
cv2_imshow( image)